name: Update README with GitHub Streak

on:
  schedule:
    # Runs at 00:00 UTC every day
    # - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub requests
          pip install PyGithub requests Pillow 
          
      - name: Update README
        run: |
          python update_streak.py
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git add assets/streak.png
          git diff --quiet && git diff --staged --quiet || git commit -m "Update contribution streak"
          git push
